#ifndef TOKENS_H_INCLUDED
#define TOKENS_H_INCLUDED

enum token {FDT, ID, NUM, PR_VAR, PR_SALIR, MAS, MAS_IGUAL, MENOS, MENOS_IGUAL, POR, POR_IGUAL, DIV, DIV_IGUAL, POT, IGUAL, PAR_IZQ, PAR_DER, NL};

#endif
